<?php

class InstitucionesSeeder extends Seeder {
    public function run (){
        DB::table('instituciones')->delete();

        $date = new DateTime();
        $date = $date->format('Y-m-d H:i:s');

        //Partidas
        DB::table('instituciones')->insert(array(
            array('id' => '1', 'tipo' => 'partida', 'nombre' => 'Presidencia de la República', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '2', 'tipo' => 'partida', 'nombre' => 'Ministerio del Interior y Seguridad Pública', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '3', 'tipo' => 'partida', 'nombre' => 'Ministerio de Relaciones Exteriores', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '4', 'tipo' => 'partida', 'nombre' => 'Ministerio de Defensa Nacional', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '5', 'tipo' => 'partida', 'nombre' => 'Ministerio de Hacienda', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '6', 'tipo' => 'partida', 'nombre' => 'Ministerio Secretaría General de la Presidencia', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '7', 'tipo' => 'partida', 'nombre' => 'Ministerio Secretaría General de Gobierno', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '8', 'tipo' => 'partida', 'nombre' => 'Ministerio de Economía, Fomento y Turismo', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '9', 'tipo' => 'partida', 'nombre' => 'Ministro de Desarrollo Social', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '10', 'tipo' => 'partida', 'nombre' => 'Ministerio de Educación', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '11', 'tipo' => 'partida', 'nombre' => 'Ministerio de Justicia', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '12', 'tipo' => 'partida', 'nombre' => 'Ministerio del Trabajo y Previsión Social', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '13', 'tipo' => 'partida', 'nombre' => 'Ministerio de Obras Públicas', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '14', 'tipo' => 'partida', 'nombre' => 'Ministerio de Transportes y Telecomunicaciones', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '15', 'tipo' => 'partida', 'nombre' => 'Ministerio de Salud', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '16', 'tipo' => 'partida', 'nombre' => 'Ministerio de Vivienda y Urbanismo', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '17', 'tipo' => 'partida', 'nombre' => 'Ministerio de Bienes Nacionales', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '18', 'tipo' => 'partida', 'nombre' => 'Ministerio de Agricultura', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '19', 'tipo' => 'partida', 'nombre' => 'Ministerio de Minería', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '20', 'tipo' => 'partida', 'nombre' => 'Servicio Nacional de la Mujer', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '21', 'tipo' => 'partida', 'nombre' => 'Ministerio de Energía', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '22', 'tipo' => 'partida', 'nombre' => 'Consejo Nacional de la Cultura y las Artes', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '23', 'tipo' => 'partida', 'nombre' => 'Ministerio del Medio Ambiente', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '24', 'tipo' => 'partida', 'nombre' => 'Consejo de Defensa del Estado', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '27', 'tipo' => 'partida', 'nombre' => 'Empresas Públicas', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '28', 'tipo' => 'partida', 'nombre' => 'Fundaciones', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '29', 'tipo' => 'partida', 'nombre' => 'Otras instituciones', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '30', 'tipo' => 'partida', 'nombre' => 'Otros poderes del Estado', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '31', 'tipo' => 'partida', 'nombre' => 'Municipios', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '32', 'tipo' => 'partida', 'nombre' => 'ChileAtiende Pymes', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '33', 'tipo' => 'partida', 'nombre' => 'ChileAtiende', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '387', 'tipo' => 'partida', 'nombre' => 'Ministerio del Deporte', 'created_at' => $date, 'updated_at' => $date)
        ));

        //Capitulos
        DB::table('instituciones')->insert(array(
            array("institucion_padre_id" => 1, "nombre" => "Presidencia de la República", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Subsecretaría del Interior", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Subsecretaría de Desarrollo Regional", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Agencia Nacional de Inteligencia", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Oficina Nacional de Emergencia", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Servicio de Gobierno Interior", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Servicio Electoral", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia Arica y Parinacota", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de Antofagasta", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de Atacama", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de Aysén", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de Coquimbo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de la Araucanía", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de Los Lagos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de Los Ríos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de Magallanes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de O’Higgins", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de Tarapacá", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia de Valparaíso", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia del Bío Bío", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia del Maule", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Intendencia Metropolitana", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Arica", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Parinacota", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Iquique", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Tamarugal", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Antofagasta", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de El Loa", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Tocopilla", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Chañaral", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Copiapó", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Huasco", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Elqui", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Limarí", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Choapa", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Petorca", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Valparaíso", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de San Felipe", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Los Andes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Quillota", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de San Antonio", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Isla de Pascua", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Cachapoal", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Colchagua", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Cardenal Caro", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Curicó", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Talca", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Linares", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Cauquenes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Ñuble", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Bío Bío", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Concepción", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Arauco", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Malleco", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Cautín", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Valdivia", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Ranco", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Osorno", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Llanquihue", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Chiloé", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Palena", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Coyhaique", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Puerto Aysén", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de General Carrera", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Capitán Prat", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Última Esperanza", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Magallanes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Tierra del Fuego", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de la Antártica Chilena", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Chacabuco", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Cordillera", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Maipo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Talagante", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Melipilla", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Arica y Parinacota", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Tarapacá", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Antofagasta", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Atacama", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Coquimbo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Valparaíso", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional Metropolitano de Santiago", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de O´Higgins", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional del Maule", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional del Bío Bío", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de La Araucanía", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Los Ríos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Los Lagos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Aysén", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobierno Regional de Magallanes y Antártica Chilena ", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Gobernación de Marga Marga", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Subsecretaría de Prevención del Delito", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Servicio Nacional de Prevención y Rehabilitación del Consumo de Drogas y Alcohol", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Departamento de Extranjería y Migración", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Carabineros de Chile", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Policía de Investigaciones", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 2, "nombre" => "Dirección de Previsión de Carabineros de Chile", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 3, "nombre" => "Subsecretaría de Relaciones Exteriores", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 3, "nombre" => "Dirección General de Relaciones Económicas Internacionales", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 3, "nombre" => "Dirección Nacional de Fronteras y Límites del Estado", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 3, "nombre" => "Agencia de Cooperación Internacional", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 3, "nombre" => "Instituto Antártico Chileno", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Subsecretaría de Guerra", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Subsecretaría de Marina", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Subsecretaría de Aviación", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Subsecretaría de Carabineros", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Subsecretaría de Investigaciones", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Ejército de Chile", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Armada de Chile", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Fuerza Aérea de Chile", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Dirección Administrativa", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Defensa Civil de Chile", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Dirección General de Movilización Nacional", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Dirección General del Territorio Marítimo y Marina Mercante", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Caja de Previsión de la Defensa Nacional", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Instituto Geográfico Militar", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Servicio Aerofotogramétrico FACh", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Servicio Hidrográfico y Oceanográfico de la Armada", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Dirección General de Aeronáutica Civil", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Subsecretaría de Defensa", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Subsecretaría para las Fuerzas Armadas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 4, "nombre" => "Estado Mayor Conjunto ", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Subsecretaría de Hacienda ", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Dirección de Presupuestos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Tesorería General de la República", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Dirección Nacional del Servicio Civil", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Unidad de Análisis Financiero", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Servicio de Impuestos Internos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Servicio Nacional de Aduanas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Superintendencia de Bancos e Instituciones Financieras", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Superintendencia de Valores y Seguros", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Dirección de Compras y Contratación Pública", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 5, "nombre" => "Superintendencia de Casinos de Juego", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 6, "nombre" => "Subsecretaría General de la Presidencia", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 6, "nombre" => "Servicio Nacional del Adulto Mayor", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 6, "nombre" => "Comisión Defensora Ciudadana", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 7, "nombre" => "Subsecretaría General de Gobierno", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 7, "nombre" => "Instituto Nacional del Deporte", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 7, "nombre" => "Consejo Nacional de Televisión", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Subsecretaría de Economía y Empresas de Menor Tamaño", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Subsecretaría de Pesca", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Comité de Inversiones Extranjeras", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Corporación de Fomento de la Producción", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Fiscalía Nacional Económica", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Instituto Nacional de Estadísticas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Servicio Nacional de Turismo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Servicio Nacional del Consumidor", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Servicio Nacional de Pesca y Acuicultura", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Subsecretaría de Turismo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Servicio de Cooperación Técnica ", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Comité Innova Bío Bío", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Superintendencia de Insolvencia y Reemprendimiento", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Instituto Nacional de Propiedad Industrial", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 8, "nombre" => "Emprendete", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 9, "nombre" => "Subsecretaría de Planificación", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 9, "nombre" => "Corporación Nacional de Desarrollo Indígena", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 9, "nombre" => "Servicio Nacional de la Discapacidad", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 9, "nombre" => "Fondo de Solidaridad e Inversión Social", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 9, "nombre" => "Instituto Nacional de la Juventud", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 9, "nombre" => "Servicio Nacional del Adulto Mayor", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 9, "nombre" => "Subsecretaría de Evaluación Social", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 9, "nombre" => "Subsecretaría de Servicios Sociales", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Subsecretaría de Educación", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Consejo de Rectores de las Universidades Chilenas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Comisión Administradora del Sistema de Créditos para Estudios Superiores (Comisión Ingresa)", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Dirección de Bibliotecas, Archivos y Museos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Consejo de Calificación Cinematográfica", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Comisión Nacional de Investigación Científica y Tecnológica", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Junta Nacional de Auxilio Escolar y Becas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Junta Nacional de Jardines Infantiles", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Agencia de Calidad de la Educación", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Consejo de Monumentos Nacionales", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Comisión Nacional de Acreditación", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Subsecretaría de Justicia", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Servicio de Registro Civil e Identificación", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Servicio Médico Legal", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Servicio Nacional de Menores", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Defensoría Penal Pública", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Gendarmería de Chile", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Corporación de Asistencia Judicial Región Metropolitana", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Corporación de Asistencia Judicial Región Valparaíso", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Corporación de Asistencia Judicial Regiones Tarapacá y Antofagasta", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 11, "nombre" => "Corporación de Asistencia Judicial Región Bío Bío", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Subsecretaría del Trabajo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Subsecretaría de Previsión Social", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Dirección del Trabajo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Dirección General de Crédito Prendario", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Instituto de Previsión Social", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Instituto de Seguridad Laboral", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Servicio Nacional de Capacitación y Empleo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Superintendencia de Pensiones", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Superintendencia de Seguridad Social", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 12, "nombre" => "Comisión del Sistema Nacional de Certificación de Competencias Laborales", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Subsecretaría de Obras Públicas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Dirección General de Obras Públicas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Dirección de Contabilidad y Finanzas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Dirección de Aeropuertos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Dirección de Arquitectura", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Dirección General de Aguas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Dirección de Obras Hidráulicas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Dirección de Obras Portuarias", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Dirección de Planeamiento", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Dirección de Vialidad", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Superintendencia de Servicios Sanitarios", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Instituto Nacional de Hidráulica", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 13, "nombre" => "Fiscalía Ministerio de Obras Públicas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 14, "nombre" => "Subsecretaría de Transportes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 14, "nombre" => "Subsecretaría de Telecomunicaciones", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 14, "nombre" => "Junta de Aeronáutica Civil", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 14, "nombre" => "Centro de Control y Certificación Vehicular", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 14, "nombre" => "Unidad Operativa de Control de Tránsito", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Subsecretaría de Salud Pública", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Subsecretaría de Redes Asistenciales", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Central de Abastecimiento del Sistema Nacional de Servicios de Salud", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Fondo Nacional de Salud", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Instituto de Salud Pública", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Superintendencia de Salud", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Metropolitano Central", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Metropolitano Norte", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Metropolitano Occidente", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Metropolitano Oriente", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Metropolitano Sur", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Metropolitano Sur Oriente", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Padre Hurtado", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Centro de Referencia de Salud de Peñalolén Cordillera Oriente", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Centro de Referencia de Salud de Maipú", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Arica", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Iquique", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Antofagasta", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Atacama", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Coquimbo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Aconcagua", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Valparaíso - San Antonio", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Viña Del Mar - Quillota", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud O´Higgins", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Maule", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Ñuble", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Concepción", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Talcahuano", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Bío Bío", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Arauco", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Araucanía Norte", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Araucanía Sur", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Valdivia", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Osorno", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud de Chiloé", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Aysén", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud del Reloncaví", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Servicio de Salud Magallanes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Arica y Parinacota", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Tarapacá", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Antofagasta", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Atacama", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Coquimbo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Valparaíso", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial Metropolitano de Santiago", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de O´Higgins", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial del Maule", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial del Bío Bío", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de La Araucanía", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Los Ríos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Los Lagos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Aysén", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Secretaría Regional Ministerial de Magallanes y Antártica Chilena", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de San Camilo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Leonardo Guzmán de Antofagasta", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Victoria", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Mauricio heyermann de Angol", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Juan Noé de Arica", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Regional de Coyhaique", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Víctor Ríos Ruiz de Los Angeles", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Dr. Augusto Riffart de Castro", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital San Jose de Coronel", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Lota", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Guillermo Grant Benavente de Concepción", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Ovalle", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital La Serena", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital San Pablo de Coquimbo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Ernesto Torres de Iquique", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "HUAP Posta central", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital San Borja Arriarán", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital San José", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Roberto del Río", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Félix Bulnes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Melipilla", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital San Juan de Dios", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Instituto Pedro Aguirre Cerda", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Instituto de Neurocirugía", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Instituto Nacional de Geriatría", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Del Salvador", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Barros Luco ", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Sótero del Río", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Lautaro Navarro de Punta Arenas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Curicó", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Linares", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Regional de Talca", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de San Carlos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital San Juan de Dios de San Fernando", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Regional de Rancagua", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Osorno", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Puerto Montt", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Tomé", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Las Higueras", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Base de Valdivia", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Claudio Vicuña de San Antonio", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Carlos Van Büren", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Eduardo Pereira de Valparaíso", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital de Quilpué", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Gustavo Fricke", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital San Martín de Quillota", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Instituto Psiquiátrico", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital San Juan de Dios de Los Andes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Exequiel González", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital El Pino", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Herminda Martin", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Instituto Nacional del Tórax", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Luis Tisné", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Instituto Traumatológico", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Instituto Nacional del Cáncer", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Luis Calvo Mackenna", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Hospital Dr. Hernán Henríquez Aravena de Temuco", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Autoridad Sanitaria", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 15, "nombre" => "Comisión de Medicina Preventiva e Invalidez", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "Subsecretaría de Vivienda y Urbanismo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de Tarapacá", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de Antofagasta", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de Atacama", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de Coquimbo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de Valparaíso", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región Metropolitana de Santiago", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región del Libertador Bernardo O'Higgins", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región del Maule", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región del Bío Bío", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de la Araucanía", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de los Lagos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de Aysén del General Carlos Ibáñez del Campo", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de Magallanes y la Antártica Chilena", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Región de Los Ríos", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "SERVIU Arica y Parinacota", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 16, "nombre" => "Parque Metropolitano de Santiago", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 17, "nombre" => "Subsecretaría de Bienes Nacionales", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 18, "nombre" => "Subsecretaría de Agricultura", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 18, "nombre" => "Comisión Nacional de Riego", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 18, "nombre" => "Instituto de Desarrollo Agropecuario", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date)
        ));

        DB::table('instituciones', array(
            array("institucion_padre_id" => 18, "nombre" => "Oficinas de Estudios y Políticas Agrarias", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 18, "nombre" => "Servicio Agrícola y Ganadero", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 19, "nombre" => "Subsecretaría de Minería", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 19, "nombre" => "Comisión Chilena del Cobre", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 19, "nombre" => "Servicio Nacional de Geología y Minería", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 20, "nombre" => "Servicio Nacional de la Mujer", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 21, "nombre" => "Ministerio de Energía", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 21, "nombre" => "Comisión Nacional de Energía", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 21, "nombre" => "Subsecretaría de Energía", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 21, "nombre" => "Comisión Chilena de Energía Nuclear", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 21, "nombre" => "Superintendencia de Electricidad y Combustibles", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 22, "nombre" => "Consejo Nacional de la Cultura y las Artes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 23, "nombre" => "Ministerio del Medio Ambiente", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 23, "nombre" => "Comisión Nacional del Medio Ambiente", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 23, "nombre" => "Subsecretaría del Medio Ambiente", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 23, "nombre" => "Superintendencia del Medio Ambiente", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 23, "nombre" => "Servicio Evaluación Ambiental", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 24, "nombre" => "Consejo de Defensa del Estado", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 10, "nombre" => "Superintendencia de Educación Escolar", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 27, "nombre" => "BancoEstado", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 27, "nombre" => "CorreosChile", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 27, "nombre" => "Diario Oficial", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 27, "nombre" => "Metro S.A.", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 27, "nombre" => "Empresa Nacional de Mineria", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 27, "nombre" => "Empresa de Ferrocarriles del Estado", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 28, "nombre" => "Fundación para la Innovación Agraria", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 28, "nombre" => "Fundación de Comunicaciones, Capacitación y Cultura", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 28, "nombre" => "Fundación de la Familia", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 28, "nombre" => "Fundación Integra", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 28, "nombre" => "Museo Interactivo Mirador", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 28, "nombre" => "Fundación Prodemu", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 29, "nombre" => "Consejo Nacional de Educación", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 29, "nombre" => "Automóvil Club de Chile", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 29, "nombre" => "Conservador de Bienes Raíces de Santiago", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 29, "nombre" => "Cajas de Compensación", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 29, "nombre" => "Corporación Nacional Forestal", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 29, "nombre" => "Comité Seguro Agrícola", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 29, "nombre" => "Instituto Nacional de Normalización", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 29, "nombre" => "Dirección de Promoción de Exportaciones", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 29, "nombre" => "Contraloría General de la República", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 30, "nombre" => "Poder Judicial", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 31, "nombre" => "Municipio", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 32, "nombre" => "ChileAtiende Pymes", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 33, "nombre" => "ChileAtiende", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date),
            array("institucion_padre_id" => 33, "nombre" => "Servicio de Pruebas", "tipo" => "capitulo", "created_at" => $date, "updated_at" => $date)
        ));
    }
} 