<?php

class SectoresSeeder extends Seeder {
    public function run (){
        DB::table('sectores')->delete();

        $date = new DateTime();
        $date = $date->format('Y-m-d H:i:s');

        //Regiones
        DB::table('sectores')->insert(array(
            array('id' => 2, 'nombre' => 'Región de Tarapacá', 'lat' => '-20.164', 'lng' => '-69.5541', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 3, 'nombre' => 'Región de Antofagasta', 'lat' => '-23.7503', 'lng' => '-69.6', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 4, 'nombre' => 'Región de Atacama', 'lat' => '-27.5276', 'lng' => '-70.2494', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 5, 'nombre' => 'Región de Coquimbo', 'lat' => '-30.8301', 'lng' => '-70.9816', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 6, 'nombre' => 'Región de Valparaíso', 'lat' => '-32.9039', 'lng' => '-71.0262', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 7, 'nombre' => 'Región del Libertador Gral. Bernardo O’Higgins', 'lat' => '-34.4294', 'lng' => '-71.0393', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 8, 'nombre' => 'Región del Maule', 'lat' => '-35.5892', 'lng' => '-71.5007', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 9, 'nombre' => 'Región del Biobío', 'lat' => '-37.2442', 'lng' => '-72.4661', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 10, 'nombre' => 'Región de la Araucanía', 'lat' => '-38.5505', 'lng' => '-72.4382', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 11, 'nombre' => 'Región de Los Lagos', 'lat' => '-42.1071', 'lng' => '-72.6425', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 12, 'nombre' => 'Región de Aysén del Gral. Carlos Ibáñez del Campo', 'lat' => '-46.2772', 'lng' => '-73.6628', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 13, 'nombre' => 'Región de Magallanes y de la Antártica Chilena', 'lat' => '-54.3551', 'lng' => '-70.5284', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 14, 'nombre' => 'Región Metropolitana de Santiago', 'lat' => '-33.4417', 'lng' => '-70.6541', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 15, 'nombre' => 'Región de Los Ríos', 'lat' => '-39.9086', 'lng' => '-72.7034', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date),
            array('id' => 16, 'nombre' => 'Región de Arica y Parinacota', 'lat' => '-18.5075', 'lng' => '-69.6451', 'tipo' => 'region', 'created_at' => $date, 'updated_at' => $date)
        ));

        //Provincias
        DB::table('sectores')->insert(array(
            array('id' => 17, 'nombre' => 'Iquique', 'lat' => '-46.2702', 'lng' => '-73.6518', 'tipo' => 'provincia', 'sector_padre_id' => 2, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 18, 'nombre' => 'Tamarugal', 'lat' => '-39.8567', 'lng' => '-72.6089', 'tipo' => 'provincia', 'sector_padre_id' => 2, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 19, 'nombre' => 'Antofagasta', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 3, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 20, 'nombre' => 'El Loa', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 3, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 21, 'nombre' => 'Tocopilla', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 3, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 22, 'nombre' => 'Copiapó', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 4, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 23, 'nombre' => 'Chañaral', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 4, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 24, 'nombre' => 'Huasco', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 4, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 25, 'nombre' => 'Elqui', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 5, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 26, 'nombre' => 'Choapa', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 5, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 27, 'nombre' => 'Limarí', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 5, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 28, 'nombre' => 'Valparaíso', 'lat' => '-33.1381', 'lng' => '-71.5617', 'tipo' => 'provincia', 'sector_padre_id' => 6, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 29, 'nombre' => 'Isla de Pascua', 'lat' => '-27.1212', 'lng' => '-109.366', 'tipo' => 'provincia', 'sector_padre_id' => 6, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 30, 'nombre' => 'Los Andes', 'lat' => '-32.9544', 'lng' => '-70.3163', 'tipo' => 'provincia', 'sector_padre_id' => 6, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 31, 'nombre' => 'Petorca', 'lat' => '-32.1965', 'lng' => '-70.8318', 'tipo' => 'provincia', 'sector_padre_id' => 6, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 32, 'nombre' => 'Quillota', 'lat' => '-32.9009', 'lng' => '-71.2947', 'tipo' => 'provincia', 'sector_padre_id' => 6, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 33, 'nombre' => 'San Antonio', 'lat' => '-33.6648', 'lng' => '-71.4597', 'tipo' => 'provincia', 'sector_padre_id' => 6, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 34, 'nombre' => 'San Felipe de Aconcagua', 'lat' => '-32.7464', 'lng' => '-70.7489', 'tipo' => 'provincia', 'sector_padre_id' => 6, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 35, 'nombre' => 'Marga Marga', 'lat' => '-33.065', 'lng' => '-71.3711', 'tipo' => 'provincia', 'sector_padre_id' => 6, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 36, 'nombre' => 'Cachapoal', 'lat' => '-36.45', 'lng' => '-71.7333', 'tipo' => 'provincia', 'sector_padre_id' => 7, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 37, 'nombre' => 'Cardenal Caro', 'lat' => '-34.2812', 'lng' => '-71.8571', 'tipo' => 'provincia', 'sector_padre_id' => 7, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 38, 'nombre' => 'Colchagua', 'lat' => '-34.6761', 'lng' => '-71.0973', 'tipo' => 'provincia', 'sector_padre_id' => 7, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 39, 'nombre' => 'Talca', 'lat' => '-35.3921', 'lng' => '-71.6125', 'tipo' => 'provincia', 'sector_padre_id' => 8, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 40, 'nombre' => 'Cauquenes', 'lat' => '-35.9738', 'lng' => '-72.3142', 'tipo' => 'provincia', 'sector_padre_id' => 8, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 41, 'nombre' => 'Curicó', 'lat' => '-35.1704', 'lng' => '-70.8954', 'tipo' => 'provincia', 'sector_padre_id' => 8, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 42, 'nombre' => 'Linares', 'lat' => '-35.8495', 'lng' => '-71.585', 'tipo' => 'provincia', 'sector_padre_id' => 8, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 43, 'nombre' => 'Concepción', 'lat' => '-36.8148', 'lng' => '-73.0293', 'tipo' => 'provincia', 'sector_padre_id' => 9, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 44, 'nombre' => 'Arauco', 'lat' => '-37.7277', 'lng' => '-73.3075', 'tipo' => 'provincia', 'sector_padre_id' => 9, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 45, 'nombre' => 'Biobío', 'lat' => '-37.4739', 'lng' => '-72.1572', 'tipo' => 'provincia', 'sector_padre_id' => 9, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 46, 'nombre' => 'Ñuble', 'lat' => '-36.6191', 'lng' => '-72.0182', 'tipo' => 'provincia', 'sector_padre_id' => 9, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 47, 'nombre' => 'Cautín', 'lat' => '-38.727', 'lng' => '-72.5989', 'tipo' => 'provincia', 'sector_padre_id' => 10, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 48, 'nombre' => 'Malleco', 'lat' => '-37.803', 'lng' => '-72.7017', 'tipo' => 'provincia', 'sector_padre_id' => 10, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 49, 'nombre' => 'Llanquihue', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 11, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 50, 'nombre' => 'Chiloé', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 11, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 51, 'nombre' => 'Osorno', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 11, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 52, 'nombre' => 'Palena', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 11, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 53, 'nombre' => 'Coihaique', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 12, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 54, 'nombre' => 'Aysén', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 12, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 55, 'nombre' => 'Capitán Prat', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 12, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 56, 'nombre' => 'General Carrera', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 12, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 57, 'nombre' => 'Magallanes', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 13, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 58, 'nombre' => 'Antártica Chilena', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 13, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 59, 'nombre' => 'Tierra del Fuego', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 13, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 60, 'nombre' => 'Última Esperanza', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 13, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 61, 'nombre' => 'Santiago', 'lat' => '-33.4417', 'lng' => '-70.6541', 'tipo' => 'provincia', 'sector_padre_id' => 14, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 62, 'nombre' => 'Cordillera', 'lat' => '-33.6984', 'lng' => '-70.1682', 'tipo' => 'provincia', 'sector_padre_id' => 14, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 63, 'nombre' => 'Chacabuco', 'lat' => '-33.1503', 'lng' => '-70.7132', 'tipo' => 'provincia', 'sector_padre_id' => 14, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 64, 'nombre' => 'Maipo', 'lat' => '-33.7963', 'lng' => '-70.7353', 'tipo' => 'provincia', 'sector_padre_id' => 14, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 65, 'nombre' => 'Melipilla', 'lat' => '-33.7369', 'lng' => '-71.1743', 'tipo' => 'provincia', 'sector_padre_id' => 14, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 66, 'nombre' => 'Talagante', 'lat' => '-33.6665', 'lng' => '-70.9331', 'tipo' => 'provincia', 'sector_padre_id' => 14, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 67, 'nombre' => 'Valdivia', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 15, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 68, 'nombre' => 'Ranco', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 15, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 69, 'nombre' => 'Arica', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 16, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 70, 'nombre' => 'Parinacota', 'lat' => '0', 'lng' => '0', 'tipo' => 'provincia', 'sector_padre_id' => 16, 'created_at' => $date, 'updated_at' => $date)
        ));

        //Comuna
        DB::table('sectores')->insert( array(
            array('id' => 71, 'nombre' => 'Iquique', 'lat' => '-20.2232', 'lng' => '-70.1463', 'tipo' => 'comuna', 'sector_padre_id' => 17, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 72, 'nombre' => 'Alto Hospicio', 'lat' => '-20.2677', 'lng' => '-70.1007', 'tipo' => 'comuna', 'sector_padre_id' => 17, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 73, 'nombre' => 'Pozo Almonte', 'lat' => '-20.2532', 'lng' => '-69.7848', 'tipo' => 'comuna', 'sector_padre_id' => 18, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 74, 'nombre' => 'Camiña', 'lat' => '-19.3118', 'lng' => '-69.4264', 'tipo' => 'comuna', 'sector_padre_id' => 18, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 75, 'nombre' => 'Colchane', 'lat' => '-19.2787', 'lng' => '-68.6343', 'tipo' => 'comuna', 'sector_padre_id' => 18, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 76, 'nombre' => 'Huara', 'lat' => '-19.9963', 'lng' => '-69.7718', 'tipo' => 'comuna', 'sector_padre_id' => 18, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 77, 'nombre' => 'Pica', 'lat' => '-20.4889', 'lng' => '-69.3289', 'tipo' => 'comuna', 'sector_padre_id' => 18, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 78, 'nombre' => 'Antofagasta', 'lat' => '-23.6499', 'lng' => '-70.4069', 'tipo' => 'comuna', 'sector_padre_id' => 19, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 79, 'nombre' => 'Mejillones', 'lat' => '-23.0962', 'lng' => '-70.4498', 'tipo' => 'comuna', 'sector_padre_id' => 19, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 80, 'nombre' => 'Sierra Gorda', 'lat' => '-22.8921', 'lng' => '-69.3203', 'tipo' => 'comuna', 'sector_padre_id' => 19, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 81, 'nombre' => 'Taltal', 'lat' => '-25.4054', 'lng' => '-70.4826', 'tipo' => 'comuna', 'sector_padre_id' => 19, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 82, 'nombre' => 'Calama', 'lat' => '-22.4542', 'lng' => '-68.9337', 'tipo' => 'comuna', 'sector_padre_id' => 20, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 83, 'nombre' => 'Ollagüe', 'lat' => '-21.2238', 'lng' => '-68.2529', 'tipo' => 'comuna', 'sector_padre_id' => 20, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 84, 'nombre' => 'San Pedro de Atacama', 'lat' => '-22.9157', 'lng' => '-68.2004', 'tipo' => 'comuna', 'sector_padre_id' => 20, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 85, 'nombre' => 'Tocopilla', 'lat' => '-22.0858', 'lng' => '-70.193', 'tipo' => 'comuna', 'sector_padre_id' => 21, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 86, 'nombre' => 'María Elena', 'lat' => '-22.1639', 'lng' => '-69.4171', 'tipo' => 'comuna', 'sector_padre_id' => 21, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 87, 'nombre' => 'Copiapó', 'lat' => '-27.3654', 'lng' => '-70.3314', 'tipo' => 'comuna', 'sector_padre_id' => 22, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 88, 'nombre' => 'Caldera', 'lat' => '-27.0668', 'lng' => '-70.817', 'tipo' => 'comuna', 'sector_padre_id' => 22, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 89, 'nombre' => 'Tierra Amarilla', 'lat' => '-27.4877', 'lng' => '-70.2696', 'tipo' => 'comuna', 'sector_padre_id' => 22, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 90, 'nombre' => 'Chañaral', 'lat' => '-26.3425', 'lng' => '-70.6107', 'tipo' => 'comuna', 'sector_padre_id' => 23, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 91, 'nombre' => 'Diego de Almagro', 'lat' => '-26.3771', 'lng' => '-70.0488', 'tipo' => 'comuna', 'sector_padre_id' => 23, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 92, 'nombre' => 'Vallenar', 'lat' => '-28.5777', 'lng' => '-70.7566', 'tipo' => 'comuna', 'sector_padre_id' => 24, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 93, 'nombre' => 'Alto del Carmen', 'lat' => '-28.7508', 'lng' => '-70.4883', 'tipo' => 'comuna', 'sector_padre_id' => 24, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 94, 'nombre' => 'Freirina', 'lat' => '-28.5001', 'lng' => '-71.076', 'tipo' => 'comuna', 'sector_padre_id' => 24, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 95, 'nombre' => 'Huasco', 'lat' => '-28.4518', 'lng' => '-71.2244', 'tipo' => 'comuna', 'sector_padre_id' => 24, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 96, 'nombre' => 'La Serena', 'lat' => '-29.8966', 'lng' => '-71.2422', 'tipo' => 'comuna', 'sector_padre_id' => 25, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 97, 'nombre' => 'Coquimbo', 'lat' => '-29.968', 'lng' => '-71.337', 'tipo' => 'comuna', 'sector_padre_id' => 25, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 98, 'nombre' => 'Andacollo', 'lat' => '-30.2357', 'lng' => '-71.0828', 'tipo' => 'comuna', 'sector_padre_id' => 25, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 99, 'nombre' => 'La Higuera', 'lat' => '-29.497', 'lng' => '-71.2656', 'tipo' => 'comuna', 'sector_padre_id' => 25, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 100, 'nombre' => 'Paiguano', 'lat' => '-30.2496', 'lng' => '-70.3832', 'tipo' => 'comuna', 'sector_padre_id' => 25, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 101, 'nombre' => 'Vicuña', 'lat' => '-30.0287', 'lng' => '-70.7108', 'tipo' => 'comuna', 'sector_padre_id' => 25, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 102, 'nombre' => 'Illapel', 'lat' => '-31.6242', 'lng' => '-71.1626', 'tipo' => 'comuna', 'sector_padre_id' => 26, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 103, 'nombre' => 'Canela', 'lat' => '-31.3935', 'lng' => '-71.4578', 'tipo' => 'comuna', 'sector_padre_id' => 26, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 104, 'nombre' => 'Los Vilos', 'lat' => '-31.9157', 'lng' => '-71.5107', 'tipo' => 'comuna', 'sector_padre_id' => 26, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 105, 'nombre' => 'Salamanca', 'lat' => '-31.7737', 'lng' => '-70.9717', 'tipo' => 'comuna', 'sector_padre_id' => 26, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 106, 'nombre' => 'Ovalle', 'lat' => '-30.5942', 'lng' => '-71.1983', 'tipo' => 'comuna', 'sector_padre_id' => 27, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 107, 'nombre' => 'Combarbalá', 'lat' => '-31.1764', 'lng' => '-70.9978', 'tipo' => 'comuna', 'sector_padre_id' => 27, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 108, 'nombre' => 'Monte Patria', 'lat' => '-30.8291', 'lng' => '-70.6984', 'tipo' => 'comuna', 'sector_padre_id' => 27, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 109, 'nombre' => 'Punitaqui', 'lat' => '-30.8256', 'lng' => '-71.2585', 'tipo' => 'comuna', 'sector_padre_id' => 27, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 110, 'nombre' => 'Río Hurtado', 'lat' => '-30.2603', 'lng' => '-70.6668', 'tipo' => 'comuna', 'sector_padre_id' => 27, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 111, 'nombre' => 'Valparaíso', 'lat' => '-33.0436', 'lng' => '-71.6231', 'tipo' => 'comuna', 'sector_padre_id' => 28, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 112, 'nombre' => 'Casablanca', 'lat' => '-33.3262', 'lng' => '-71.3983', 'tipo' => 'comuna', 'sector_padre_id' => 28, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 113, 'nombre' => 'Concón', 'lat' => '-32.9305', 'lng' => '-71.5191', 'tipo' => 'comuna', 'sector_padre_id' => 28, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 114, 'nombre' => 'Juan Fernández', 'lat' => '-33.6167', 'lng' => '-78.8667', 'tipo' => 'comuna', 'sector_padre_id' => 28, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 115, 'nombre' => 'Puchuncaví', 'lat' => '-32.7499', 'lng' => '-71.396', 'tipo' => 'comuna', 'sector_padre_id' => 28, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 116, 'nombre' => 'Quintero', 'lat' => '-32.7872', 'lng' => '-71.5274', 'tipo' => 'comuna', 'sector_padre_id' => 28, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 117, 'nombre' => 'Viña del Mar', 'lat' => '-33.0445', 'lng' => '-71.5224', 'tipo' => 'comuna', 'sector_padre_id' => 28, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 118, 'nombre' => 'Isla de Pascua', 'lat' => '-27.1504', 'lng' => '-109.423', 'tipo' => 'comuna', 'sector_padre_id' => 29, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 119, 'nombre' => 'Los Andes', 'lat' => '-32.8347', 'lng' => '-70.5971', 'tipo' => 'comuna', 'sector_padre_id' => 30, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 120, 'nombre' => 'Calle Larga', 'lat' => '-32.9514', 'lng' => '-70.5524', 'tipo' => 'comuna', 'sector_padre_id' => 30, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 121, 'nombre' => 'Rinconada', 'lat' => '-32.8765', 'lng' => '-70.7085', 'tipo' => 'comuna', 'sector_padre_id' => 30, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 122, 'nombre' => 'San Esteban', 'lat' => '-32.693', 'lng' => '-70.3703', 'tipo' => 'comuna', 'sector_padre_id' => 30, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 123, 'nombre' => 'La Ligua', 'lat' => '-32.449', 'lng' => '-71.2309', 'tipo' => 'comuna', 'sector_padre_id' => 31, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 124, 'nombre' => 'Cabildo', 'lat' => '-32.4095', 'lng' => '-71.0798', 'tipo' => 'comuna', 'sector_padre_id' => 31, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 125, 'nombre' => 'Papudo', 'lat' => '-32.4699', 'lng' => '-71.3842', 'tipo' => 'comuna', 'sector_padre_id' => 31, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 126, 'nombre' => 'Petorca', 'lat' => '-32.1965', 'lng' => '-70.8318', 'tipo' => 'comuna', 'sector_padre_id' => 31, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 127, 'nombre' => 'Zapallar', 'lat' => '-32.5933', 'lng' => '-71.3686', 'tipo' => 'comuna', 'sector_padre_id' => 31, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 128, 'nombre' => 'Quillota', 'lat' => '-32.8793', 'lng' => '-71.2508', 'tipo' => 'comuna', 'sector_padre_id' => 32, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 129, 'nombre' => 'Calera', 'lat' => '-32.7837', 'lng' => '-71.1586', 'tipo' => 'comuna', 'sector_padre_id' => 32, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 130, 'nombre' => 'Hijuelas', 'lat' => '-32.8671', 'lng' => '-71.0929', 'tipo' => 'comuna', 'sector_padre_id' => 32, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 131, 'nombre' => 'La Cruz', 'lat' => '-32.8258', 'lng' => '-71.2592', 'tipo' => 'comuna', 'sector_padre_id' => 32, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 132, 'nombre' => 'Nogales', 'lat' => '-32.6923', 'lng' => '-71.1894', 'tipo' => 'comuna', 'sector_padre_id' => 32, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 133, 'nombre' => 'San Antonio', 'lat' => '-33.5812', 'lng' => '-71.613', 'tipo' => 'comuna', 'sector_padre_id' => 33, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 134, 'nombre' => 'Algarrobo', 'lat' => '-33.3332', 'lng' => '-71.6023', 'tipo' => 'comuna', 'sector_padre_id' => 33, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 135, 'nombre' => 'Cartagena', 'lat' => '-33.5341', 'lng' => '-71.4628', 'tipo' => 'comuna', 'sector_padre_id' => 33, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 136, 'nombre' => 'El Quisco', 'lat' => '-33.4156', 'lng' => '-71.6556', 'tipo' => 'comuna', 'sector_padre_id' => 33, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 137, 'nombre' => 'El Tabo', 'lat' => '-33.4847', 'lng' => '-71.5862', 'tipo' => 'comuna', 'sector_padre_id' => 33, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 138, 'nombre' => 'Santo Domingo', 'lat' => '-33.7076', 'lng' => '-71.6301', 'tipo' => 'comuna', 'sector_padre_id' => 33, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 139, 'nombre' => 'San Felipe', 'lat' => '-32.7464', 'lng' => '-70.7489', 'tipo' => 'comuna', 'sector_padre_id' => 34, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 140, 'nombre' => 'Catemu', 'lat' => '-32.6981', 'lng' => '-70.956', 'tipo' => 'comuna', 'sector_padre_id' => 34, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 141, 'nombre' => 'Llay Llay', 'lat' => '-32.8899', 'lng' => '-70.8942', 'tipo' => 'comuna', 'sector_padre_id' => 34, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 142, 'nombre' => 'Panquehue', 'lat' => '-32.8079', 'lng' => '-70.8428', 'tipo' => 'comuna', 'sector_padre_id' => 34, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 143, 'nombre' => 'Putaendo', 'lat' => '-32.6279', 'lng' => '-70.7165', 'tipo' => 'comuna', 'sector_padre_id' => 34, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 144, 'nombre' => 'Santa María', 'lat' => '-32.7446', 'lng' => '-70.654', 'tipo' => 'comuna', 'sector_padre_id' => 34, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 145, 'nombre' => 'Quilpué', 'lat' => '-33.0492', 'lng' => '-71.4435', 'tipo' => 'comuna', 'sector_padre_id' => 35, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 146, 'nombre' => 'Limache', 'lat' => '-33.0035', 'lng' => '-71.2613', 'tipo' => 'comuna', 'sector_padre_id' => 35, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 147, 'nombre' => 'Olmué', 'lat' => '-33.0132', 'lng' => '-71.1525', 'tipo' => 'comuna', 'sector_padre_id' => 35, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 148, 'nombre' => 'Villa Alemana', 'lat' => '-33.0429', 'lng' => '-71.3724', 'tipo' => 'comuna', 'sector_padre_id' => 35, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 149, 'nombre' => 'Rancagua', 'lat' => '-34.162', 'lng' => '-70.741', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 150, 'nombre' => 'Codegua', 'lat' => '-34.0442', 'lng' => '-70.5131', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 151, 'nombre' => 'Coinco', 'lat' => '-34.2918', 'lng' => '-70.9706', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 152, 'nombre' => 'Coltauco', 'lat' => '-34.2498', 'lng' => '-71.0791', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 153, 'nombre' => 'Doñihue', 'lat' => '-34.2024', 'lng' => '-70.9325', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 154, 'nombre' => 'Graneros', 'lat' => '-34.0709', 'lng' => '-70.7501', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 155, 'nombre' => 'Las Cabras', 'lat' => '-34.2945', 'lng' => '-71.3066', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 156, 'nombre' => 'Machalí', 'lat' => '-34.2938', 'lng' => '-70.3371', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 157, 'nombre' => 'Malloa', 'lat' => '-34.4455', 'lng' => '-70.9449', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 158, 'nombre' => 'Mostazal', 'lat' => '-33.9772', 'lng' => '-70.7092', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 159, 'nombre' => 'Olivar', 'lat' => '-34.2186', 'lng' => '-70.8355', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 160, 'nombre' => 'Peumo', 'lat' => '-34.3798', 'lng' => '-71.1687', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 161, 'nombre' => 'Pichidegua', 'lat' => '-34.3758', 'lng' => '-71.3469', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 162, 'nombre' => 'Quinta de Tilcoco', 'lat' => '-34.367', 'lng' => '-71.0096', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 163, 'nombre' => 'Rengo', 'lat' => '-34.4017', 'lng' => '-70.8561', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 164, 'nombre' => 'Requínoa', 'lat' => '-34.3533', 'lng' => '-70.6797', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 165, 'nombre' => 'San Vicente', 'lat' => '-34.4381', 'lng' => '-71.0792', 'tipo' => 'comuna', 'sector_padre_id' => 36, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 166, 'nombre' => 'Pichilemu', 'lat' => '-34.3869', 'lng' => '-72.0032', 'tipo' => 'comuna', 'sector_padre_id' => 37, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 167, 'nombre' => 'La Estrella', 'lat' => '-34.2037', 'lng' => '-71.6073', 'tipo' => 'comuna', 'sector_padre_id' => 37, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 168, 'nombre' => 'Litueche', 'lat' => '-34.1069', 'lng' => '-71.7204', 'tipo' => 'comuna', 'sector_padre_id' => 37, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 169, 'nombre' => 'Marchihue', 'lat' => '-34.3979', 'lng' => '-71.6144', 'tipo' => 'comuna', 'sector_padre_id' => 37, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 170, 'nombre' => 'Navidad', 'lat' => '-34.0068', 'lng' => '-71.8101', 'tipo' => 'comuna', 'sector_padre_id' => 37, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 171, 'nombre' => 'Paredones', 'lat' => '-34.6972', 'lng' => '-71.8978', 'tipo' => 'comuna', 'sector_padre_id' => 37, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 172, 'nombre' => 'San Fernando', 'lat' => '-34.584', 'lng' => '-70.9874', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 173, 'nombre' => 'Chépica', 'lat' => '-34.7303', 'lng' => '-71.2688', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 174, 'nombre' => 'Chimbarongo', 'lat' => '-34.7552', 'lng' => '-70.9753', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 175, 'nombre' => 'Lolol', 'lat' => '-34.7689', 'lng' => '-71.6453', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 176, 'nombre' => 'Nancagua', 'lat' => '-34.6615', 'lng' => '-71.1749', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 177, 'nombre' => 'Palmilla', 'lat' => '-34.6042', 'lng' => '-71.3583', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 178, 'nombre' => 'Peralillo', 'lat' => '-34.4593', 'lng' => '-71.5', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 179, 'nombre' => 'Placilla', 'lat' => '-34.6135', 'lng' => '-71.0951', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 180, 'nombre' => 'Pumanque', 'lat' => '-34.6052', 'lng' => '-71.6443', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 181, 'nombre' => 'Santa Cruz', 'lat' => '-34.6383', 'lng' => '-71.367', 'tipo' => 'comuna', 'sector_padre_id' => 38, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 182, 'nombre' => 'Talca', 'lat' => '-35.4288', 'lng' => '-71.6607', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 183, 'nombre' => 'Constitución', 'lat' => '-35.3309', 'lng' => '-72.4139', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 184, 'nombre' => 'Curepto', 'lat' => '-35.091', 'lng' => '-72.0216', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 185, 'nombre' => 'Empedrado', 'lat' => '-35.6213', 'lng' => '-72.2473', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 186, 'nombre' => 'Maule', 'lat' => '-35.5057', 'lng' => '-71.7069', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 187, 'nombre' => 'Pelarco', 'lat' => '-35.3723', 'lng' => '-71.3278', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 188, 'nombre' => 'Pencahue', 'lat' => '-35.3051', 'lng' => '-71.8284', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 189, 'nombre' => 'Río Claro', 'lat' => '-35.2827', 'lng' => '-71.2665', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 190, 'nombre' => 'San Clemente', 'lat' => '-35.534', 'lng' => '-71.4865', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 191, 'nombre' => 'San Rafael', 'lat' => '-35.2942', 'lng' => '-71.5254', 'tipo' => 'comuna', 'sector_padre_id' => 39, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 192, 'nombre' => 'Cauquenes', 'lat' => '-35.9738', 'lng' => '-72.3142', 'tipo' => 'comuna', 'sector_padre_id' => 40, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 193, 'nombre' => 'Chanco', 'lat' => '-35.7337', 'lng' => '-72.5333', 'tipo' => 'comuna', 'sector_padre_id' => 40, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 194, 'nombre' => 'Pelluhue', 'lat' => '-35.8145', 'lng' => '-72.5736', 'tipo' => 'comuna', 'sector_padre_id' => 40, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 195, 'nombre' => 'Curicó', 'lat' => '-34.9756', 'lng' => '-71.2235', 'tipo' => 'comuna', 'sector_padre_id' => 41, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 196, 'nombre' => 'Hualañé', 'lat' => '-34.9762', 'lng' => '-71.8043', 'tipo' => 'comuna', 'sector_padre_id' => 41, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 197, 'nombre' => 'Licantén', 'lat' => '-34.9591', 'lng' => '-72.0269', 'tipo' => 'comuna', 'sector_padre_id' => 41, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 198, 'nombre' => 'Molina', 'lat' => '-35.0896', 'lng' => '-71.2788', 'tipo' => 'comuna', 'sector_padre_id' => 41, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 199, 'nombre' => 'Rauco', 'lat' => '-34.9295', 'lng' => '-71.3111', 'tipo' => 'comuna', 'sector_padre_id' => 41, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 200, 'nombre' => 'Romeral', 'lat' => '-34.9634', 'lng' => '-71.1205', 'tipo' => 'comuna', 'sector_padre_id' => 41, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 201, 'nombre' => 'Sagrada Familia', 'lat' => '-34.9949', 'lng' => '-71.3798', 'tipo' => 'comuna', 'sector_padre_id' => 41, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 202, 'nombre' => 'Teno', 'lat' => '-34.8701', 'lng' => '-71.0895', 'tipo' => 'comuna', 'sector_padre_id' => 41, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 203, 'nombre' => 'Vichuquén', 'lat' => '-34.8594', 'lng' => '-72.0074', 'tipo' => 'comuna', 'sector_padre_id' => 41, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 204, 'nombre' => 'Linares', 'lat' => '-35.8495', 'lng' => '-71.585', 'tipo' => 'comuna', 'sector_padre_id' => 42, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 205, 'nombre' => 'Colbún', 'lat' => '-35.6927', 'lng' => '-71.4067', 'tipo' => 'comuna', 'sector_padre_id' => 42, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 206, 'nombre' => 'Longaví', 'lat' => '-35.9657', 'lng' => '-71.6816', 'tipo' => 'comuna', 'sector_padre_id' => 42, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 207, 'nombre' => 'Parral', 'lat' => '-36.14', 'lng' => '-71.8244', 'tipo' => 'comuna', 'sector_padre_id' => 42, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 208, 'nombre' => 'Retiro', 'lat' => '-36.0458', 'lng' => '-71.7591', 'tipo' => 'comuna', 'sector_padre_id' => 42, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 209, 'nombre' => 'San Javier', 'lat' => '-35.6035', 'lng' => '-71.7362', 'tipo' => 'comuna', 'sector_padre_id' => 42, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 210, 'nombre' => 'Villa Alegre', 'lat' => '-35.6868', 'lng' => '-71.6704', 'tipo' => 'comuna', 'sector_padre_id' => 42, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 211, 'nombre' => 'Yerbas Buenas', 'lat' => '-35.6882', 'lng' => '-71.5636', 'tipo' => 'comuna', 'sector_padre_id' => 42, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 212, 'nombre' => 'Concepción', 'lat' => '-36.8148', 'lng' => '-73.0293', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 213, 'nombre' => 'Coronel', 'lat' => '-37.0265', 'lng' => '-73.1498', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 214, 'nombre' => 'Chiguayante', 'lat' => '-36.9046', 'lng' => '-73.0164', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 215, 'nombre' => 'Florida', 'lat' => '-36.8209', 'lng' => '-72.6621', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 216, 'nombre' => 'Hualqui', 'lat' => '-37.0145', 'lng' => '-72.8662', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 217, 'nombre' => 'Lota', 'lat' => '-37.0906', 'lng' => '-73.1547', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 218, 'nombre' => 'Penco', 'lat' => '-36.7423', 'lng' => '-72.998', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 219, 'nombre' => 'San Pedro de la Paz', 'lat' => '-36.8635', 'lng' => '-73.1085', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 220, 'nombre' => 'Santa Juana', 'lat' => '-37.1726', 'lng' => '-72.9352', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 221, 'nombre' => 'Talcahuano', 'lat' => '-36.7364', 'lng' => '-73.1047', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 222, 'nombre' => 'Tomé', 'lat' => '-36.6177', 'lng' => '-72.9579', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 223, 'nombre' => 'Hualpén', 'lat' => '-36.7827', 'lng' => '-73.1454', 'tipo' => 'comuna', 'sector_padre_id' => 43, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 224, 'nombre' => 'Lebu', 'lat' => '-37.6079', 'lng' => '-73.6508', 'tipo' => 'comuna', 'sector_padre_id' => 44, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 225, 'nombre' => 'Arauco', 'lat' => '-37.257', 'lng' => '-73.2839', 'tipo' => 'comuna', 'sector_padre_id' => 44, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 226, 'nombre' => 'Cañete', 'lat' => '-37.8039', 'lng' => '-73.4016', 'tipo' => 'comuna', 'sector_padre_id' => 44, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 227, 'nombre' => 'Contulmo', 'lat' => '-38.026', 'lng' => '-73.2581', 'tipo' => 'comuna', 'sector_padre_id' => 44, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 228, 'nombre' => 'Curanilahue', 'lat' => '-37.4759', 'lng' => '-73.353', 'tipo' => 'comuna', 'sector_padre_id' => 44, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 229, 'nombre' => 'Los Álamos', 'lat' => '-37.6747', 'lng' => '-73.3896', 'tipo' => 'comuna', 'sector_padre_id' => 44, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 230, 'nombre' => 'Tirúa', 'lat' => '-38.3315', 'lng' => '-73.3794', 'tipo' => 'comuna', 'sector_padre_id' => 44, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 231, 'nombre' => 'Los Ángeles', 'lat' => '-37.473', 'lng' => '-72.3507', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 232, 'nombre' => 'Antuco', 'lat' => '-37.3273', 'lng' => '-71.6775', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 233, 'nombre' => 'Cabrero', 'lat' => '-37.0374', 'lng' => '-72.4057', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 234, 'nombre' => 'Laja', 'lat' => '-37.2768', 'lng' => '-72.7171', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 235, 'nombre' => 'Mulchén', 'lat' => '-37.7147', 'lng' => '-72.2394', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 236, 'nombre' => 'Nacimiento', 'lat' => '-37.5011', 'lng' => '-72.6763', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 237, 'nombre' => 'Negrete', 'lat' => '-37.5974', 'lng' => '-72.5646', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 238, 'nombre' => 'Quilaco', 'lat' => '-37.6799', 'lng' => '-72.0074', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 239, 'nombre' => 'Quilleco', 'lat' => '-37.4335', 'lng' => '-71.8761', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 240, 'nombre' => 'San Rosendo', 'lat' => '-37.2021', 'lng' => '-72.748', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 241, 'nombre' => 'Santa Bárbara', 'lat' => '-37.6627', 'lng' => '-72.0184', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 242, 'nombre' => 'Tucapel', 'lat' => '-37.2901', 'lng' => '-71.9491', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 243, 'nombre' => 'Yumbel', 'lat' => '-37.0964', 'lng' => '-72.5562', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 244, 'nombre' => 'Alto Biobío', 'lat' => '-37.8708', 'lng' => '-71.6106', 'tipo' => 'comuna', 'sector_padre_id' => 45, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 245, 'nombre' => 'Chillán', 'lat' => '-36.6013', 'lng' => '-72.1093', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 246, 'nombre' => 'Bulnes', 'lat' => '-36.7422', 'lng' => '-72.3018', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 247, 'nombre' => 'Cobquecura', 'lat' => '-36.1318', 'lng' => '-72.7911', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 248, 'nombre' => 'Coelemu', 'lat' => '-36.4877', 'lng' => '-72.7022', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 249, 'nombre' => 'Coihueco', 'lat' => '-36.6166', 'lng' => '-71.8344', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 250, 'nombre' => 'Chillán Viejo', 'lat' => '-36.6333', 'lng' => '-72.1404', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 251, 'nombre' => 'El Carmen', 'lat' => '-36.8964', 'lng' => '-72.0218', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 252, 'nombre' => 'Ninhue', 'lat' => '-36.4011', 'lng' => '-72.397', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 253, 'nombre' => 'Ñiquén', 'lat' => '-36.2848', 'lng' => '-71.8994', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 254, 'nombre' => 'Pemuco', 'lat' => '-36.9865', 'lng' => '-72.0191', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 255, 'nombre' => 'Pinto', 'lat' => '-36.6978', 'lng' => '-71.8934', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 256, 'nombre' => 'Portezuelo', 'lat' => '-36.529', 'lng' => '-72.433', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 257, 'nombre' => 'Quillón', 'lat' => '-36.7383', 'lng' => '-72.469', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 258, 'nombre' => 'Quirihue', 'lat' => '-36.2839', 'lng' => '-72.5414', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 259, 'nombre' => 'Ránquil', 'lat' => '-36.6485', 'lng' => '-72.6064', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 260, 'nombre' => 'San Carlos', 'lat' => '-36.4221', 'lng' => '-71.9594', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 261, 'nombre' => 'San Fabián', 'lat' => '-36.5538', 'lng' => '-71.5487', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 262, 'nombre' => 'San Ignacio', 'lat' => '-36.8186', 'lng' => '-71.9883', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 263, 'nombre' => 'San Nicolás', 'lat' => '-36.4996', 'lng' => '-72.2126', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 264, 'nombre' => 'Treguaco', 'lat' => '-36.4095', 'lng' => '-72.6603', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 265, 'nombre' => 'Yungay', 'lat' => '-37.122', 'lng' => '-72.0132', 'tipo' => 'comuna', 'sector_padre_id' => 46, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 266, 'nombre' => 'Temuco', 'lat' => '-38.7362', 'lng' => '-72.5989', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 267, 'nombre' => 'Carahue', 'lat' => '-38.7116', 'lng' => '-73.1651', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 268, 'nombre' => 'Cunco', 'lat' => '-38.9307', 'lng' => '-72.0264', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 269, 'nombre' => 'Curarrehue', 'lat' => '-39.3592', 'lng' => '-71.5881', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 270, 'nombre' => 'Freire', 'lat' => '-38.9538', 'lng' => '-72.6219', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 271, 'nombre' => 'Galvarino', 'lat' => '-38.4085', 'lng' => '-72.7804', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 272, 'nombre' => 'Gorbea', 'lat' => '-39.0948', 'lng' => '-72.6722', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 273, 'nombre' => 'Lautaro', 'lat' => '-38.5286', 'lng' => '-72.427', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 274, 'nombre' => 'Loncoche', 'lat' => '-39.3681', 'lng' => '-72.6315', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 275, 'nombre' => 'Melipeuco', 'lat' => '-38.8429', 'lng' => '-71.6871', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 276, 'nombre' => 'Nueva Imperial', 'lat' => '-38.7445', 'lng' => '-72.9482', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 277, 'nombre' => 'Padre las Casas', 'lat' => '-38.7658', 'lng' => '-72.5929', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 278, 'nombre' => 'Perquenco', 'lat' => '-38.4154', 'lng' => '-72.3725', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 279, 'nombre' => 'Pitrufquén', 'lat' => '-38.9829', 'lng' => '-72.6429', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 280, 'nombre' => 'Pucón', 'lat' => '-39.2824', 'lng' => '-71.9545', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 281, 'nombre' => 'Saavedra', 'lat' => '-38.7803', 'lng' => '-73.3897', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 282, 'nombre' => 'Teodoro Schmidt', 'lat' => '-38.9989', 'lng' => '-73.093', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 283, 'nombre' => 'Toltén', 'lat' => '-39.2022', 'lng' => '-73.2004', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 284, 'nombre' => 'Vilcún', 'lat' => '-38.6701', 'lng' => '-72.2238', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 285, 'nombre' => 'Villarrica', 'lat' => '-39.2803', 'lng' => '-72.2182', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 286, 'nombre' => 'Cholchol', 'lat' => '-38.596', 'lng' => '-72.8445', 'tipo' => 'comuna', 'sector_padre_id' => 47, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 287, 'nombre' => 'Angol', 'lat' => '-37.803', 'lng' => '-72.7017', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 288, 'nombre' => 'Collipulli', 'lat' => '-37.9528', 'lng' => '-72.4323', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 289, 'nombre' => 'Curacautín', 'lat' => '-38.4317', 'lng' => '-71.8898', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 290, 'nombre' => 'Ercilla', 'lat' => '-38.0587', 'lng' => '-72.358', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 291, 'nombre' => 'Lonquimay', 'lat' => '-38.4501', 'lng' => '-71.374', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 292, 'nombre' => 'Los Sauces', 'lat' => '-37.9754', 'lng' => '-72.8288', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 293, 'nombre' => 'Lumaco', 'lat' => '-38.1636', 'lng' => '-72.8918', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 294, 'nombre' => 'Purén', 'lat' => '-38.0326', 'lng' => '-73.0728', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 295, 'nombre' => 'Renaico', 'lat' => '-37.6654', 'lng' => '-72.5687', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 296, 'nombre' => 'Traiguén', 'lat' => '-38.2509', 'lng' => '-72.6647', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 297, 'nombre' => 'Victoria', 'lat' => '-38.2336', 'lng' => '-72.3329', 'tipo' => 'comuna', 'sector_padre_id' => 48, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 298, 'nombre' => 'Puerto Montt', 'lat' => '-41.4633', 'lng' => '-72.9314', 'tipo' => 'comuna', 'sector_padre_id' => 49, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 299, 'nombre' => 'Calbuco', 'lat' => '-41.7775', 'lng' => '-73.1415', 'tipo' => 'comuna', 'sector_padre_id' => 49, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 300, 'nombre' => 'Cochamó', 'lat' => '-41.488', 'lng' => '-72.3038', 'tipo' => 'comuna', 'sector_padre_id' => 49, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 301, 'nombre' => 'Fresia', 'lat' => '-41.1542', 'lng' => '-73.4224', 'tipo' => 'comuna', 'sector_padre_id' => 49, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 302, 'nombre' => 'Frutillar', 'lat' => '-41.1167', 'lng' => '-73.05', 'tipo' => 'comuna', 'sector_padre_id' => 49, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 303, 'nombre' => 'Los Muermos', 'lat' => '-41.3997', 'lng' => '-73.4651', 'tipo' => 'comuna', 'sector_padre_id' => 49, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 304, 'nombre' => 'Llanquihue', 'lat' => '-41.2574', 'lng' => '-73.0054', 'tipo' => 'comuna', 'sector_padre_id' => 49, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 305, 'nombre' => 'Maullín', 'lat' => '-41.6172', 'lng' => '-73.5956', 'tipo' => 'comuna', 'sector_padre_id' => 49, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 306, 'nombre' => 'Puerto Varas', 'lat' => '-41.316', 'lng' => '-72.9836', 'tipo' => 'comuna', 'sector_padre_id' => 49, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 307, 'nombre' => 'Castro', 'lat' => '-42.48', 'lng' => '-73.7625', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 308, 'nombre' => 'Ancud', 'lat' => '-41.8657', 'lng' => '-73.8336', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 309, 'nombre' => 'Chonchi', 'lat' => '-42.6232', 'lng' => '-73.7739', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 310, 'nombre' => 'Curaco de Vélez', 'lat' => '-42.4404', 'lng' => '-73.6037', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 311, 'nombre' => 'Dalcahue', 'lat' => '-42.3776', 'lng' => '-73.6521', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 312, 'nombre' => 'Puqueldón', 'lat' => '-42.6015', 'lng' => '-73.6714', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 313, 'nombre' => 'Queilén', 'lat' => '-42.9001', 'lng' => '-73.4827', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 314, 'nombre' => 'Quellón', 'lat' => '-43.1156', 'lng' => '-73.6172', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 315, 'nombre' => 'Quemchi', 'lat' => '-42.1426', 'lng' => '-73.475', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 316, 'nombre' => 'Quinchao', 'lat' => '-42.472', 'lng' => '-73.4898', 'tipo' => 'comuna', 'sector_padre_id' => 50, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 317, 'nombre' => 'Osorno', 'lat' => '-40.5747', 'lng' => '-73.1319', 'tipo' => 'comuna', 'sector_padre_id' => 51, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 318, 'nombre' => 'Puerto Octay', 'lat' => '-40.9755', 'lng' => '-72.8833', 'tipo' => 'comuna', 'sector_padre_id' => 51, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 319, 'nombre' => 'Purranque', 'lat' => '-40.9085', 'lng' => '-73.1653', 'tipo' => 'comuna', 'sector_padre_id' => 51, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 320, 'nombre' => 'Puyehue', 'lat' => '-40.6806', 'lng' => '-72.599', 'tipo' => 'comuna', 'sector_padre_id' => 51, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 321, 'nombre' => 'Río Negro', 'lat' => '-40.7829', 'lng' => '-73.2319', 'tipo' => 'comuna', 'sector_padre_id' => 51, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 322, 'nombre' => 'San Juan de la Costa', 'lat' => '-40.5156', 'lng' => '-73.3997', 'tipo' => 'comuna', 'sector_padre_id' => 51, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 323, 'nombre' => 'San Pablo', 'lat' => '-40.4118', 'lng' => '-73.0102', 'tipo' => 'comuna', 'sector_padre_id' => 51, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 324, 'nombre' => 'Chaitén', 'lat' => '-42.9168', 'lng' => '-72.7164', 'tipo' => 'comuna', 'sector_padre_id' => 52, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 325, 'nombre' => 'Futaleufú', 'lat' => '-43.1859', 'lng' => '-71.8666', 'tipo' => 'comuna', 'sector_padre_id' => 52, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 326, 'nombre' => 'Hualaihué', 'lat' => '-42.0967', 'lng' => '-72.4044', 'tipo' => 'comuna', 'sector_padre_id' => 52, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 327, 'nombre' => 'Palena', 'lat' => '-43.6162', 'lng' => '-71.8176', 'tipo' => 'comuna', 'sector_padre_id' => 52, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 328, 'nombre' => 'Coihaique', 'lat' => '-45.5758', 'lng' => '-72.0621', 'tipo' => 'comuna', 'sector_padre_id' => 53, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 329, 'nombre' => 'Lago Verde', 'lat' => '-44.2236', 'lng' => '-71.8396', 'tipo' => 'comuna', 'sector_padre_id' => 53, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 330, 'nombre' => 'Aysén', 'lat' => '-45.3975', 'lng' => '-72.6993', 'tipo' => 'comuna', 'sector_padre_id' => 54, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 331, 'nombre' => 'Cisnes', 'lat' => '-44.728', 'lng' => '-72.6828', 'tipo' => 'comuna', 'sector_padre_id' => 54, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 332, 'nombre' => 'Guaitecas', 'lat' => '-43.8781', 'lng' => '-73.7485', 'tipo' => 'comuna', 'sector_padre_id' => 54, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 333, 'nombre' => 'Cochrane', 'lat' => '-47.2494', 'lng' => '-72.5784', 'tipo' => 'comuna', 'sector_padre_id' => 55, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 334, 'nombre' => 'O’Higgins', 'lat' => '-48.4643', 'lng' => '-72.5613', 'tipo' => 'comuna', 'sector_padre_id' => 55, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 335, 'nombre' => 'Tortel', 'lat' => '-47.8242', 'lng' => '-73.5645', 'tipo' => 'comuna', 'sector_padre_id' => 55, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 336, 'nombre' => 'Chile Chico', 'lat' => '-46.5401', 'lng' => '-71.7218', 'tipo' => 'comuna', 'sector_padre_id' => 56, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 337, 'nombre' => 'Río Ibáñez', 'lat' => '-46.2938', 'lng' => '-71.9357', 'tipo' => 'comuna', 'sector_padre_id' => 56, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 338, 'nombre' => 'Punta Arenas', 'lat' => '-53.1641', 'lng' => '-70.9305', 'tipo' => 'comuna', 'sector_padre_id' => 57, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 339, 'nombre' => 'Laguna Blanca', 'lat' => '-52.3001', 'lng' => '-71.1612', 'tipo' => 'comuna', 'sector_padre_id' => 57, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 340, 'nombre' => 'Río Verde', 'lat' => '-52.5814', 'lng' => '-71.5128', 'tipo' => 'comuna', 'sector_padre_id' => 57, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 341, 'nombre' => 'San Gregorio', 'lat' => '-52.3135', 'lng' => '-69.6842', 'tipo' => 'comuna', 'sector_padre_id' => 57, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 342, 'nombre' => 'Antártica', 'lat' => '-64.3589', 'lng' => '-60.8203', 'tipo' => 'comuna', 'sector_padre_id' => 58, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 343, 'nombre' => 'Porvenir', 'lat' => '-53.2898', 'lng' => '-70.3633', 'tipo' => 'comuna', 'sector_padre_id' => 59, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 344, 'nombre' => 'Primavera', 'lat' => '-52.7122', 'lng' => '-69.2496', 'tipo' => 'comuna', 'sector_padre_id' => 59, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 345, 'nombre' => 'Timaukel', 'lat' => '-54.2877', 'lng' => '-69.1644', 'tipo' => 'comuna', 'sector_padre_id' => 59, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 346, 'nombre' => 'Natales', 'lat' => '-51.7219', 'lng' => '-72.5208', 'tipo' => 'comuna', 'sector_padre_id' => 60, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 347, 'nombre' => 'Torres del Paine', 'lat' => '-50.9896', 'lng' => '-73.0893', 'tipo' => 'comuna', 'sector_padre_id' => 60, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 348, 'nombre' => 'Santiago Centro', 'lat' => '-33.4417', 'lng' => '-70.6541', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 349, 'nombre' => 'Cerrillos', 'lat' => '-33.497', 'lng' => '-70.7112', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 350, 'nombre' => 'Cerro Navia', 'lat' => '-33.4267', 'lng' => '-70.7434', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 351, 'nombre' => 'Conchalí', 'lat' => '-33.3862', 'lng' => '-70.6727', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 352, 'nombre' => 'El Bosque', 'lat' => '-33.5638', 'lng' => '-70.6714', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 353, 'nombre' => 'Estación Central', 'lat' => '-33.4503', 'lng' => '-70.6751', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 354, 'nombre' => 'Huechuraba', 'lat' => '-33.3665', 'lng' => '-70.6315', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 355, 'nombre' => 'Independencia', 'lat' => '-33.4196', 'lng' => '-70.6627', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 356, 'nombre' => 'La Cisterna', 'lat' => '-33.538', 'lng' => '-70.6612', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 357, 'nombre' => 'La Florida', 'lat' => '-33.5225', 'lng' => '-70.5952', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 358, 'nombre' => 'La Granja', 'lat' => '-33.5373', 'lng' => '-70.6188', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 359, 'nombre' => 'La Pintana', 'lat' => '-33.5902', 'lng' => '-70.6322', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 360, 'nombre' => 'La Reina', 'lat' => '-33.4565', 'lng' => '-70.5349', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 361, 'nombre' => 'Las Condes', 'lat' => '-33.4154', 'lng' => '-70.5837', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 362, 'nombre' => 'Lo Barnechea', 'lat' => '-33.2993', 'lng' => '-70.3748', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 363, 'nombre' => 'Lo Espejo', 'lat' => '-33.5247', 'lng' => '-70.6916', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 364, 'nombre' => 'Lo Prado', 'lat' => '-33.4489', 'lng' => '-70.721', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 365, 'nombre' => 'Macul', 'lat' => '-33.492', 'lng' => '-70.5968', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 366, 'nombre' => 'Maipú', 'lat' => '-33.5213', 'lng' => '-70.7572', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 367, 'nombre' => 'Ñuñoa', 'lat' => '-33.4607', 'lng' => '-70.5927', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 368, 'nombre' => 'Pedro Aguirre Cerda', 'lat' => '-33.4891', 'lng' => '-70.6729', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 369, 'nombre' => 'Peñalolén', 'lat' => '-33.4904', 'lng' => '-70.5105', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 370, 'nombre' => 'Providencia', 'lat' => '-33.4214', 'lng' => '-70.6033', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 371, 'nombre' => 'Pudahuel', 'lat' => '-33.4184', 'lng' => '-70.8324', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 372, 'nombre' => 'Quilicura', 'lat' => '-33.3551', 'lng' => '-70.7278', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 373, 'nombre' => 'Quinta Normal', 'lat' => '-33.428', 'lng' => '-70.6964', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 374, 'nombre' => 'Recoleta', 'lat' => '-33.4173', 'lng' => '-70.6303', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 375, 'nombre' => 'Renca', 'lat' => '-33.4141', 'lng' => '-70.7129', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 376, 'nombre' => 'San Joaquín', 'lat' => '-33.4961', 'lng' => '-70.6245', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 377, 'nombre' => 'San Miguel', 'lat' => '-33.5017', 'lng' => '-70.6489', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 378, 'nombre' => 'San Ramón', 'lat' => '-33.5349', 'lng' => '-70.6392', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 379, 'nombre' => 'Vitacura', 'lat' => '-33.3863', 'lng' => '-70.5698', 'tipo' => 'comuna', 'sector_padre_id' => 61, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 380, 'nombre' => 'Puente Alto', 'lat' => '-33.6079', 'lng' => '-70.5778', 'tipo' => 'comuna', 'sector_padre_id' => 62, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 381, 'nombre' => 'Pirque', 'lat' => '-33.7384', 'lng' => '-70.4914', 'tipo' => 'comuna', 'sector_padre_id' => 62, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 382, 'nombre' => 'San José de Maipo', 'lat' => '-33.6921', 'lng' => '-70.1325', 'tipo' => 'comuna', 'sector_padre_id' => 62, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 383, 'nombre' => 'Colina', 'lat' => '-33.1996', 'lng' => '-70.6702', 'tipo' => 'comuna', 'sector_padre_id' => 63, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 384, 'nombre' => 'Lampa', 'lat' => '-33.2863', 'lng' => '-70.8789', 'tipo' => 'comuna', 'sector_padre_id' => 63, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 385, 'nombre' => 'Tiltil', 'lat' => '-33.0655', 'lng' => '-70.8465', 'tipo' => 'comuna', 'sector_padre_id' => 63, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 386, 'nombre' => 'San Bernardo', 'lat' => '-33.5913', 'lng' => '-70.702', 'tipo' => 'comuna', 'sector_padre_id' => 64, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 387, 'nombre' => 'Buin', 'lat' => '-33.754', 'lng' => '-70.7163', 'tipo' => 'comuna', 'sector_padre_id' => 64, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 388, 'nombre' => 'Calera de Tango', 'lat' => '-33.6326', 'lng' => '-70.7821', 'tipo' => 'comuna', 'sector_padre_id' => 64, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 389, 'nombre' => 'Paine', 'lat' => '-33.8673', 'lng' => '-70.7303', 'tipo' => 'comuna', 'sector_padre_id' => 64, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 390, 'nombre' => 'Melipilla', 'lat' => '-33.6866', 'lng' => '-71.2139', 'tipo' => 'comuna', 'sector_padre_id' => 65, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 391, 'nombre' => 'Alhué', 'lat' => '-34.0355', 'lng' => '-71.028', 'tipo' => 'comuna', 'sector_padre_id' => 65, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 392, 'nombre' => 'Curacaví', 'lat' => '-33.4063', 'lng' => '-71.1333', 'tipo' => 'comuna', 'sector_padre_id' => 65, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 393, 'nombre' => 'María Pinto', 'lat' => '-33.5154', 'lng' => '-71.1191', 'tipo' => 'comuna', 'sector_padre_id' => 65, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 394, 'nombre' => 'San Pedro', 'lat' => '-33.8779', 'lng' => '-71.4609', 'tipo' => 'comuna', 'sector_padre_id' => 65, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 395, 'nombre' => 'Talagante', 'lat' => '-33.6643', 'lng' => '-70.9296', 'tipo' => 'comuna', 'sector_padre_id' => 66, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 396, 'nombre' => 'El Monte', 'lat' => '-33.6662', 'lng' => '-71.0294', 'tipo' => 'comuna', 'sector_padre_id' => 66, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 397, 'nombre' => 'Isla de Maipo', 'lat' => '-33.7536', 'lng' => '-70.8862', 'tipo' => 'comuna', 'sector_padre_id' => 66, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 398, 'nombre' => 'Padre Hurtado', 'lat' => '-33.5761', 'lng' => '-70.8003', 'tipo' => 'comuna', 'sector_padre_id' => 66, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 399, 'nombre' => 'Peñaflor', 'lat' => '-33.6141', 'lng' => '-70.8876', 'tipo' => 'comuna', 'sector_padre_id' => 66, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 400, 'nombre' => 'Valdivia', 'lat' => '-39.8201', 'lng' => '-73.2457', 'tipo' => 'comuna', 'sector_padre_id' => 67, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 401, 'nombre' => 'Corral', 'lat' => '-39.8892', 'lng' => '-73.433', 'tipo' => 'comuna', 'sector_padre_id' => 67, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 402, 'nombre' => 'Lanco', 'lat' => '-39.4522', 'lng' => '-72.7747', 'tipo' => 'comuna', 'sector_padre_id' => 67, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 403, 'nombre' => 'Los Lagos', 'lat' => '-39.8636', 'lng' => '-72.8124', 'tipo' => 'comuna', 'sector_padre_id' => 67, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 404, 'nombre' => 'Máfil', 'lat' => '-39.6654', 'lng' => '-72.9575', 'tipo' => 'comuna', 'sector_padre_id' => 67, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 405, 'nombre' => 'Mariquina', 'lat' => '-39.5399', 'lng' => '-72.9621', 'tipo' => 'comuna', 'sector_padre_id' => 67, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 406, 'nombre' => 'Paillaco', 'lat' => '-40.0707', 'lng' => '-72.8708', 'tipo' => 'comuna', 'sector_padre_id' => 67, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 407, 'nombre' => 'Panguipulli', 'lat' => '-39.6436', 'lng' => '-72.3365', 'tipo' => 'comuna', 'sector_padre_id' => 67, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 408, 'nombre' => 'La Unión', 'lat' => '-40.2951', 'lng' => '-73.0829', 'tipo' => 'comuna', 'sector_padre_id' => 68, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 409, 'nombre' => 'Futrono', 'lat' => '-40.1243', 'lng' => '-72.393', 'tipo' => 'comuna', 'sector_padre_id' => 68, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 410, 'nombre' => 'Lago Ranco', 'lat' => '-40.312', 'lng' => '-72.5002', 'tipo' => 'comuna', 'sector_padre_id' => 68, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 411, 'nombre' => 'Río Bueno', 'lat' => '-40.333', 'lng' => '-72.9513', 'tipo' => 'comuna', 'sector_padre_id' => 68, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 412, 'nombre' => 'Arica', 'lat' => '-18.477', 'lng' => '-70.3221', 'tipo' => 'comuna', 'sector_padre_id' => 69, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 413, 'nombre' => 'Camarones', 'lat' => '-19.0089', 'lng' => '-69.9074', 'tipo' => 'comuna', 'sector_padre_id' => 69, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 414, 'nombre' => 'Putre', 'lat' => '-18.1798', 'lng' => '-69.5544', 'tipo' => 'comuna', 'sector_padre_id' => 70, 'created_at' => $date, 'updated_at' => $date),
            array('id' => 415, 'nombre' => 'General Lagos', 'lat' => '-17.8324', 'lng' => '-69.6094', 'tipo' => 'comuna', 'sector_padre_id' => 70, 'created_at' => $date, 'updated_at' => $date)
        ));
    }
} 